// Generated by `node shoot-lab-cards.mjs`. Do not edit by hand.
//
// One content hash per gallery card, appended to its URL so a reshoot is
// visible immediately: the images keep their filenames and `public/_headers`
// caches them for a day.
// สร้างจากสคริปต์ ห้ามแก้มือ

export const labCardVersions: Record<string, string> = {
  "gaze": "d3f69857",
  "meeple": "08a29a94",
  "slab": "83a94b72",
  "ember": "451faf74",
  "unfold": "c4cc480f",
  "trine": "ac85a815",
  "cart": "85ba7b6a",
  "counter": "37137618",
  "longtail": "ab96eabe",
  "stall": "6e1e6e44",
  "minimal": "41711562"
};
