// Generated by `node shoot-lab-cards.mjs`. Do not edit by hand.
//
// One content hash per gallery card, appended to its URL so a reshoot is
// visible immediately: the images keep their filenames and `public/_headers`
// caches them for a day.
// สร้างจากสคริปต์ ห้ามแก้มือ

export const labCardVersions: Record<string, string> = {
  "contour": "b3b5398b",
  "trine": "30b3d780",
  "sable": "0252e4ff",
  "meridian": "c12cd25c",
  "cart": "43928dfd",
  "counter": "b046cbbd",
  "longtail": "c14b4ce7",
  "stall": "a594baea",
  "playroom": "e3c40b29",
  "dimension": "4d8f96c6",
  "vision": "578ce9b6",
  "space": "fbeba2e2",
  "luxe": "7be50997",
  "minimal": "7874f897"
};
