// Generated by `node shoot-lab-cards.mjs`. Do not edit by hand.
//
// One content hash per gallery card, appended to its URL so a reshoot is
// visible immediately: the images keep their filenames and `public/_headers`
// caches them for a day.
// สร้างจากสคริปต์ ห้ามแก้มือ

export const labCardVersions: Record<string, string> = {
  "contour": "953be926",
  "unfold": "c4cc480f",
  "trine": "ac85a815",
  "sable": "422d2181",
  "meridian": "62b55d5b",
  "cart": "85ba7b6a",
  "counter": "37137618",
  "longtail": "ab96eabe",
  "stall": "6e1e6e44",
  "playroom": "7577d738",
  "signal": "375b08f2",
  "terminal": "0819d577",
  "dimension": "82f2bb66",
  "vision": "32b3cd49",
  "space": "756433aa",
  "luxe": "ed1dc801",
  "minimal": "41711562"
};
